// =====================================================================
// Messages shown while descending/loading (the audit is running).
// 300+ entries — players wait 10-15 minutes, so variety is critical.
// Tone: dark, brooding, low fantasy. Despair, dread, isolation, decay.
// =====================================================================
export const DESCENT_MESSAGES = [
  // ── Original ──
  "The air grows thin.",
  "Steel on stone.",
  "Deeper.",
  "No turning back.",
  "Something shifted below.",
  "The walls are wet.",
  "Torch won't last.",
  "Bones underfoot.",
  "The dark thickens.",
  "It knows you're here.",
  "Keep moving.",
  "The stairs have no end.",
  "Cold iron. Cold air.",
  "A sound. Then nothing.",
  "The weight of stone above.",
  "Dripping. Steady. Close.",
  "Your shadow left you.",

  // ── Batch 1: Darkness and descent ──
  "The torch dims without wind.",
  "Dripping. Always dripping.",
  "Cold stone remembers nothing.",
  "Something moved in the dark.",
  "The walls are wet here.",
  "Your breath clouds and fades.",
  "Iron taste on your tongue.",
  "The echo did not return.",
  "Deeper than the roots go.",
  "Bones ground to white dust.",
  "The dark has weight here.",
  "No light from above now.",
  "Silence louder than screaming.",
  "The steps behind you stopped.",
  "Water finds the lowest place.",
  "Rust and rot and stone.",
  "You are not the first.",
  "The ceiling presses down slowly.",
  "Old blood on old iron.",
  "Something breathes in the dark.",
  "Your shadow moves without you.",
  "Walls slick with cold seep.",
  "The air has no memory.",
  "Down is the only direction.",
  "These halls swallowed their builders.",
  "The dark is not empty.",
  "Footsteps fill with standing water.",
  "The cold is awake here.",
  "Nothing grows this deep down.",
  "Wet stone. Faint iron smell.",
  "The dark watches. It waits.",
  "Ribs in the settling dust.",
  "Even your name fades here.",
  "The passage narrows. Always.",
  "There is no morning here.",
  "Fingers wore grooves in stone.",
  "The weight of earth above.",
  "Somewhere, a door closes itself.",
  "Your light is borrowed time.",
  "Moss covers what screamed last.",
  "The stairwell has no bottom.",
  "Black water. Do not drink.",
  "The rot smells like memory.",
  "Something old settled in the walls.",
  "Stone does not forget footsteps.",
  "The dark is older here.",
  "A sound. Then nothing. Then—",
  "The pit goes further down.",
  "Cold hands left these marks.",
  "The flame leans toward nothing.",
  "Hollow sockets in hollow stone.",
  "These halls were not built.",
  "The dark grows thicker below.",
  "Your heartbeat sounds very loud.",
  "Dust from where the ceiling sags.",
  "The water runs toward something.",
  "Iron doors. No handles inside.",
  "The dark has learned patience.",
  "Old stone, older silence.",
  "The passage does not widen.",
  "Something was dragged through here.",
  "Your torch makes shadows move.",
  "The steps are worn smooth.",
  "Not all who descended returned.",
  "The air sits heavy here.",
  "Cracks in stone. Old cracks.",
  "The dark has texture now.",
  "Teeth marks on the doorframe.",
  "The cold enters the bones.",
  "Your reflection is not there.",
  "The tunnel bends away from light.",
  "Water drips through ancient seams.",
  "Whatever lived here left bones.",
  "The dark does not mind waiting.",
  "Stone remembers pressure.",
  "The silence is a sound.",
  "The word means less now.",
  "No wind. No sound. Descend.",

  // ── Batch 2: Scratching, corpses, sealed passages ──
  "Something scratched and went still.",
  "The passage narrows ahead.",
  "Rust and old blood.",
  "A door, sealed from within.",
  "The chains hang empty.",
  "Footsteps that are not yours.",
  "The walls sweat in the cold.",
  "Another corpse faced downward.",
  "Silence after the settling stone.",
  "The smell of turned earth.",
  "Torchlight does not reach the ceiling.",
  "A name carved into the floor.",
  "The stairs continue past the map.",
  "Breathing that is not breathing.",
  "Mud seals the lower passage.",
  "Someone died reaching for the wall.",
  "The echo returns wrong.",
  "Iron rings, no chains attached.",
  "Three doors. Two collapsed.",
  "Wet stone. No water source.",
  "Old smoke stains on the ceiling.",
  "A torch burned down to nothing.",
  "The corridor bends and bends.",
  "Scratching inside the sealed wall.",
  "Roots have broken through the stone.",
  "The cold comes from below.",
  "A pile of discarded tools.",
  "The lantern oil is nearly gone.",
  "Bones arranged with care.",
  "The rot smell thickens here.",
  "Eyes in the dark, or none.",
  "The door opens both ways.",
  "A hand, reaching from rubble.",
  "Something watches from the high ledge.",
  "The floor gives slightly underfoot.",
  "Mold in the shape of fingers.",
  "The passage was sealed from outside.",
  "A belt buckle, no body near.",
  "The stone here is scorched.",
  "Whatever it was, it crawled.",
  "The torch gutters and holds.",
  "A shallow grave, unmarked.",
  "Dust on the inside of the door.",
  "Something soft beneath the gravel.",
  "The ceiling drips black.",
  "An open lock with no chain.",
  "Fingernail marks on the stone.",
  "The corridor ends in earth.",
  "Something left its shell behind.",
  "The dark absorbs the torchlight.",
  "A voice, very far below.",
  "Rubble still warm from collapse.",
  "The smell of iron and sleep.",
  "Another level down. Another still.",
  "The wood of the door is soft.",
  "A shadow that does not move.",
  "The footprints stop mid-corridor.",
  "Teeth marks in the mortar.",
  "The crack in the ceiling widens.",
  "Everything here died slowly.",
  "A pile of coins, untouched.",
  "The dark does not echo.",
  "Dust falls without disturbance.",
  "The walls are closer than before.",
  "An open book, pages rotted blank.",
  "The steps descend without counting.",
  "Something lives in the drain.",
  "A rope, cut near the anchor.",
  "The passage smells of long waiting.",
  "Stone dust settles on the dead.",
  "The door was opened from below.",
  "Nothing moves. Nothing has moved.",

  // ── Batch 3: Forgotten kingdoms, futility ──
  "The walls remember everything.",
  "Something moved ahead.",
  "No one sent you here.",
  "You have forgotten the sun.",
  "This corridor was sealed for reasons.",
  "The mechanism still turns.",
  "Bone dust on the floor.",
  "Something breathed here recently.",
  "The inscription has been scratched out.",
  "There are no exits marked.",
  "The chains are old. The locks are not.",
  "The burial rites were never finished.",
  "Deeper means darker.",
  "The throne room sits empty.",
  "Whatever built this is still here.",
  "The descent continues.",
  "A child's drawing on the wall.",
  "The floor is warm.",
  "These were once streets.",
  "The archive burned from within.",
  "You are below the graves now.",
  "The last cartographer stopped here.",
  "They feared what they worshipped.",
  "The ropes have long since rotted.",
  "The altars face the wrong direction.",
  "Stone wears down. The dark does not.",
  "You count steps. You lose count.",
  "The empire was thorough in its erasure.",
  "The collapse came from below.",
  "The lanterns were deliberately broken.",
  "You follow marks left in desperation.",
  "The dead were stacked, not buried.",
  "This level was not on the map.",
  "The architecture makes no sense.",
  "Whatever they dug for, they found it.",
  "You pass through where others stopped.",
  "The name of this place was removed.",
  "The pillars are compressed ash.",
  "You have been walking for hours.",
  "The shadows do not move with light.",
  "The scripture here is a warning.",
  "The bridge holds. Barely.",
  "The locks were sealed from outside.",
  "The roots have reached this depth.",
  "Nothing decays here. Nothing ends.",
  "The veins in the rock pulse faintly.",
  "A shrine to an unknown grief.",
  "The ceiling has faces in it.",
  "The workers never left.",
  "This chamber was meant to be forgotten.",
  "The last fire was a long time ago.",
  "Whatever they built outlasted them.",
  "You move through a long exhale.",
  "The gears have not stopped turning.",
  "Stone absorbs the sound of steps.",
  "The hunger is manageable. For now.",
  "Whatever bled here, bled long.",
  "These halls were built to confuse.",
  "A figure carved to look away.",
  "The water here is black and still.",
  "You have passed this mark before.",
  "The dark is consistent. You are not.",
  "The floor slopes. You did not notice.",
  "There is no going back up.",

  // ── Batch 4: Weapons of the fallen, dead gods ──
  "The torch remembers nothing.",
  "Something breathes behind the wall.",
  "Your map ends here.",
  "The stone is always wet.",
  "No echo returns.",
  "A sword, no hand to hold it.",
  "The gods have other concerns.",
  "Bones ground to dust by boots.",
  "The air tastes of old iron.",
  "Whatever prayed here was not heard.",
  "The compass needle cannot decide.",
  "Armor split at the seam.",
  "The altar holds nothing sacred now.",
  "Your footsteps sound like someone else.",
  "A helmet, visor facing down.",
  "No name carved on this grave.",
  "The dark is patient.",
  "Wet earth, fresh displacement.",
  "This passage was not here before.",
  "A lantern, still warm.",
  "The chain leads nowhere useful.",
  "Ribs spread open like a book.",
  "The shrine was not abandoned gently.",
  "Something learned your rhythm.",
  "The ceiling is lower than before.",
  "Prayers worn into stone by fingers.",
  "The wound in the wall seeps.",
  "A shield, dented from within.",
  "The rot has tenure here.",
  "Scuttling, then silence, then scuttling.",
  "The north means nothing underground.",
  "Candle wax, no candle.",
  "Someone scratched a warning, then stopped.",
  "The second staircase descends further.",
  "A gauntlet, palm up, empty.",
  "The sound arrives before the cause.",
  "This god stopped answering long ago.",
  "The floor is softer than stone.",
  "The lock is on the wrong side.",
  "Spores, not dust.",
  "A cloak, still holding a shape.",
  "The dark folds in on itself.",
  "Three passages, all familiar.",
  "The well has no bottom sound.",
  "Your shadow leans the wrong way.",
  "Blood older than memory.",
  "Teeth marks on the torch handle.",
  "The inscription ends mid-sentence.",
  "A boot, one boot.",
  "The fungus glows without warmth.",
  "Something has been counting the days.",
  "The walls remember pressure.",
  "An offering, rejected and left.",
  "You breathe slower without knowing.",
  "Something feeds on the quiet.",
  "Calcified hands still gripping stone.",
  "The idol's face has been removed.",
  "Your light reaches less than before.",
  "A crossbow, bolt still loaded.",
  "The corridor lists to the left.",
  "Water comes through but does not leave.",
  "The smell changes before the creature.",
  "The passage remembers the flood.",
  "A body positioned like it chose this.",
  "Rust the color of old wounds.",
  "Whatever lived here did not leave.",
  "The next room sounds the same.",
  "A dagger in the floor.",
  "The silence has texture now.",
];

// Messages shown when a demon is first encountered in battle
export const ENCOUNTER_MESSAGES = [
  "It reeks of rot.",
  "This one's fast.",
  "Teeth. Too many teeth.",
  "It was waiting.",
  "Stand your ground.",
  "Ugly thing.",
  "It doesn't blink.",
  "Wrong turn.",
  "Big. Angry.",
  "Eyes in the dark.",
  "It heard you coming.",
  "The stench hits first.",
  "Older than the dungeon.",
  "It unfolds from the wall.",
  "Not dead. Never was.",
  "The ground shakes beneath it.",
  "It remembers your kind.",
  "Too close to run.",
  "The dark parts around it.",
  "It doesn't need to breathe.",
  "Cornered. Both of you.",
  "Its patience ends now.",
  "The torch flickers near it.",
  "Bone and sinew. Nothing else.",
  "It smiles without a mouth.",
];

// Messages shown after defeating a demon
export const VICTORY_MESSAGES = [
  "It's done.",
  "One less.",
  "The blood dries quick.",
  "Won't miss that one.",
  "Still standing.",
  "Barely.",
  "On to the next.",
  "It stayed down.",
  "Good riddance.",
  "Wounds heal. Move on.",
  "The dark feels lighter.",
  "The stench remains.",
  "It fell apart slowly.",
  "Silence returns.",
  "Not pretty. But done.",
  "The blade held.",
  "One fewer shadow.",
  "It did not die quietly.",
  "The floor drinks what's left.",
  "Press on.",
  "You're still bleeding.",
  "That was close.",
  "Mark the wall. Move on.",
  "The echoes settle.",
  "Better it than you.",
];

// Messages for the dungeon hall (shown as subtitle/flavor)
export const HALL_MESSAGES = [
  "They're all waiting.",
  "Pick your kill.",
  "So many.",
  "One at a time.",
  "The hall reeks of them.",
  "Choose wisely.",
  "The worst ones hide at the top.",
  "They know your name.",
  "Each one worse than the last.",
  "The dungeon does not empty easily.",
];
